
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import bean.Person;
import people.Resource;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.ws.rs.core.Response;

import org.junit.Before;

public class ResourceTest {
	Person p = new Person();

	@Before
	public void setData() {
		p.setName("it");
		p.setAge(23);
		p.setAddress("address");
		Map<String, String> m = new LinkedHashMap<String, String>();
		m.put("mobile", "1234");
		m.put("home", "5678");
		List<Map<String, String>> l = new ArrayList<Map<String, String>>();
		l.add(m);
		p.setTelNumbers(l);

	}

	@Test
	public void testResourceClass() {
		Resource resource = new Resource();

		Response getResponse = resource.getPeople();
		assertNotNull(getResponse);

		Response updateResponse = resource.updatePeople(p);
		assertNotNull(updateResponse);

	}
}
